name: Unit Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install -g pnpm@7.23.0
          pnpm i
          pnpm test
